-- Phase 6C follow-up: preserve publish SEO metadata across schema variants
-- Adds the legacy publish metadata columns that are absent from the 006 marketplace
-- inventory_seo shape but still generated by the publish route.

ALTER TABLE inventory_seo
  ADD COLUMN IF NOT EXISTS og_image_url TEXT,
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS canonical_url TEXT;

CREATE INDEX IF NOT EXISTS idx_inventory_seo_slug ON inventory_seo(slug) WHERE slug IS NOT NULL;
